name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        node-version-file: .nvmrc

    - name: Upgrade npm for trusted publishing
      run: npm install -g npm@latest
      shell: bash

    - name: Install dependencies
      run: |
        npm ci
        npm ci --prefix example
      shell: bash
