name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - ".github/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - ".github/**"

jobs:
  static-analysis:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: npm run eslint -- --max-warnings=0

      - name: Typecheck files
        run: npm run typecheck

      - name: Format check
        run: npm run prettier -- --check

  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Install Ionic and Cordova
        run: npm install -g @ionic/cli cordova

      - name: Add Android platform
        run: |
          cd example/
          ionic cordova platform add android --confirm

      - name: Build Android
        run: |
          cd example/
          ionic cordova build android --confirm
